name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npx eslint --ext .js,.jsx src test
      - name: Run unit tests
        run: npm run test:unit
      - name: Build
        run: |
          npx webpack --mode=production
          npm run build
          cp -r dist/bundle-*.js public/
          cp -r dist/*.png public/
          cp -r assets public/
          cp dist/index.html public/404.html
          cp favicon.ico public/
      - name: Run E2E tests
        run: |
          cp -r _test/* test/
          HEADLESS=true npm run test:ci-e2e
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: main
          BRANCH: gh-pages
          FOLDER: public
